language: minimal

os:
  - linux

dist: focal

install:
  - sudo apt-get -y install cc65

script:
  - ca65 --cpu 65816 -s -o cake-w.o cake-w.s
  - ld65 -C memmap.cfg -o cake-w.sfc cake-w.o

before_deploy:
  - git config --local user.name "$GIT_NAME"
  - git config --local user.email "$GIT_EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GH_TOKEN
  name: CAKEW build $(date +'%d.%m.%Y %R')
  file:
    - "cake-w.sfc"
  on:
    branch: master
